# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FormationEditor.ui'
#
# Created: Sun Jun 29 18:04:02 2008
#      by: PyQt4 UI code generator 4.4.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(806,698)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setGeometry(QtCore.QRect(0,21,806,658))
        self.centralwidget.setObjectName("centralwidget")
        self.hboxlayout = QtGui.QHBoxLayout(self.centralwidget)
        self.hboxlayout.setObjectName("hboxlayout")
        self.Preview = QtGui.QGroupBox(self.centralwidget)
        self.Preview.setObjectName("Preview")
        self.gridlayout = QtGui.QGridLayout(self.Preview)
        self.gridlayout.setObjectName("gridlayout")
        self.PreviewArea = QtGui.QScrollArea(self.Preview)
        self.PreviewArea.setWidgetResizable(False)
        self.PreviewArea.setObjectName("PreviewArea")
        self.gridlayout.addWidget(self.PreviewArea,0,0,1,1)
        self.hboxlayout.addWidget(self.Preview)
        self.ToolBox = QtGui.QGroupBox(self.centralwidget)
        self.ToolBox.setMaximumSize(QtCore.QSize(200,16777215))
        self.ToolBox.setBaseSize(QtCore.QSize(100,0))
        self.ToolBox.setObjectName("ToolBox")
        self.vboxlayout = QtGui.QVBoxLayout(self.ToolBox)
        self.vboxlayout.setObjectName("vboxlayout")
        self.PathGroup = QtGui.QGroupBox(self.ToolBox)
        self.PathGroup.setObjectName("PathGroup")
        self.vboxlayout1 = QtGui.QVBoxLayout(self.PathGroup)
        self.vboxlayout1.setObjectName("vboxlayout1")
        self.Curve = QtGui.QRadioButton(self.PathGroup)
        self.Curve.setChecked(True)
        self.Curve.setObjectName("Curve")
        self.vboxlayout1.addWidget(self.Curve)
        self.Line = QtGui.QRadioButton(self.PathGroup)
        self.Line.setObjectName("Line")
        self.vboxlayout1.addWidget(self.Line)
        self.AddPath = QtGui.QPushButton(self.PathGroup)
        self.AddPath.setObjectName("AddPath")
        self.vboxlayout1.addWidget(self.AddPath)
        self.DeletePath = QtGui.QPushButton(self.PathGroup)
        self.DeletePath.setObjectName("DeletePath")
        self.vboxlayout1.addWidget(self.DeletePath)
        self.vboxlayout.addWidget(self.PathGroup)
        self.AssociateGroup = QtGui.QGroupBox(self.ToolBox)
        self.AssociateGroup.setObjectName("AssociateGroup")
        self.vboxlayout2 = QtGui.QVBoxLayout(self.AssociateGroup)
        self.vboxlayout2.setObjectName("vboxlayout2")
        self.WhenEnd = QtGui.QRadioButton(self.AssociateGroup)
        self.WhenEnd.setChecked(True)
        self.WhenEnd.setObjectName("WhenEnd")
        self.vboxlayout2.addWidget(self.WhenEnd)
        self.WhenPlayerIsFound = QtGui.QRadioButton(self.AssociateGroup)
        self.WhenPlayerIsFound.setObjectName("WhenPlayerIsFound")
        self.vboxlayout2.addWidget(self.WhenPlayerIsFound)
        self.AssociateButton = QtGui.QPushButton(self.AssociateGroup)
        self.AssociateButton.setObjectName("AssociateButton")
        self.vboxlayout2.addWidget(self.AssociateButton)
        self.vboxlayout.addWidget(self.AssociateGroup)
        self.PenwidthGroup = QtGui.QGroupBox(self.ToolBox)
        self.PenwidthGroup.setObjectName("PenwidthGroup")
        self.vboxlayout3 = QtGui.QVBoxLayout(self.PenwidthGroup)
        self.vboxlayout3.setObjectName("vboxlayout3")
        self.PenWidthSlider = QtGui.QSlider(self.PenwidthGroup)
        self.PenWidthSlider.setOrientation(QtCore.Qt.Horizontal)
        self.PenWidthSlider.setObjectName("PenWidthSlider")
        self.vboxlayout3.addWidget(self.PenWidthSlider)
        self.vboxlayout.addWidget(self.PenwidthGroup)
        self.MonsterGroup = QtGui.QGroupBox(self.ToolBox)
        self.MonsterGroup.setObjectName("MonsterGroup")
        self.vboxlayout4 = QtGui.QVBoxLayout(self.MonsterGroup)
        self.vboxlayout4.setObjectName("vboxlayout4")
        self.PreviewWidget = QtGui.QWidget(self.MonsterGroup)
        self.PreviewWidget.setObjectName("PreviewWidget")
        self.hboxlayout1 = QtGui.QHBoxLayout(self.PreviewWidget)
        self.hboxlayout1.setObjectName("hboxlayout1")
        self.PreviewLabel = QtGui.QLabel(self.PreviewWidget)
        self.PreviewLabel.setObjectName("PreviewLabel")
        self.hboxlayout1.addWidget(self.PreviewLabel)
        self.widget_3 = QtGui.QWidget(self.PreviewWidget)
        self.widget_3.setObjectName("widget_3")
        self.hboxlayout1.addWidget(self.widget_3)
        self.vboxlayout4.addWidget(self.PreviewWidget)
        self.SizeWidget = QtGui.QWidget(self.MonsterGroup)
        self.SizeWidget.setObjectName("SizeWidget")
        self.hboxlayout2 = QtGui.QHBoxLayout(self.SizeWidget)
        self.hboxlayout2.setObjectName("hboxlayout2")
        self.SizeLabel = QtGui.QLabel(self.SizeWidget)
        self.SizeLabel.setObjectName("SizeLabel")
        self.hboxlayout2.addWidget(self.SizeLabel)
        self.SizeSlider = QtGui.QSlider(self.SizeWidget)
        self.SizeSlider.setMinimum(1)
        self.SizeSlider.setMaximum(5)
        self.SizeSlider.setPageStep(1)
        self.SizeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.SizeSlider.setTickPosition(QtGui.QSlider.TicksAbove)
        self.SizeSlider.setObjectName("SizeSlider")
        self.hboxlayout2.addWidget(self.SizeSlider)
        self.vboxlayout4.addWidget(self.SizeWidget)
        self.ColorWidget = QtGui.QWidget(self.MonsterGroup)
        self.ColorWidget.setObjectName("ColorWidget")
        self.hboxlayout3 = QtGui.QHBoxLayout(self.ColorWidget)
        self.hboxlayout3.setObjectName("hboxlayout3")
        self.ColorLabel = QtGui.QLabel(self.ColorWidget)
        self.ColorLabel.setObjectName("ColorLabel")
        self.hboxlayout3.addWidget(self.ColorLabel)
        self.ColorSlider = QtGui.QSlider(self.ColorWidget)
        self.ColorSlider.setMinimum(1)
        self.ColorSlider.setMaximum(5)
        self.ColorSlider.setPageStep(1)
        self.ColorSlider.setOrientation(QtCore.Qt.Horizontal)
        self.ColorSlider.setTickPosition(QtGui.QSlider.TicksAbove)
        self.ColorSlider.setObjectName("ColorSlider")
        self.hboxlayout3.addWidget(self.ColorSlider)
        self.vboxlayout4.addWidget(self.ColorWidget)
        self.AddChange = QtGui.QPushButton(self.MonsterGroup)
        self.AddChange.setObjectName("AddChange")
        self.vboxlayout4.addWidget(self.AddChange)
        self.vboxlayout.addWidget(self.MonsterGroup)
        self.GlobalGroup = QtGui.QGroupBox(self.ToolBox)
        self.GlobalGroup.setObjectName("GlobalGroup")
        self.vboxlayout5 = QtGui.QVBoxLayout(self.GlobalGroup)
        self.vboxlayout5.setObjectName("vboxlayout5")
        self.Animate = QtGui.QPushButton(self.GlobalGroup)
        self.Animate.setObjectName("Animate")
        self.vboxlayout5.addWidget(self.Animate)
        self.Save = QtGui.QPushButton(self.GlobalGroup)
        self.Save.setObjectName("Save")
        self.vboxlayout5.addWidget(self.Save)
        self.vboxlayout.addWidget(self.GlobalGroup)
        self.hboxlayout.addWidget(self.ToolBox)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0,0,806,21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setGeometry(QtCore.QRect(0,679,806,19))
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.Preview.setTitle(QtGui.QApplication.translate("MainWindow", "Preview", None, QtGui.QApplication.UnicodeUTF8))
        self.ToolBox.setTitle(QtGui.QApplication.translate("MainWindow", "Tools", None, QtGui.QApplication.UnicodeUTF8))
        self.PathGroup.setTitle(QtGui.QApplication.translate("MainWindow", "Path", None, QtGui.QApplication.UnicodeUTF8))
        self.Curve.setText(QtGui.QApplication.translate("MainWindow", "Curve", None, QtGui.QApplication.UnicodeUTF8))
        self.Line.setText(QtGui.QApplication.translate("MainWindow", "Line", None, QtGui.QApplication.UnicodeUTF8))
        self.AddPath.setText(QtGui.QApplication.translate("MainWindow", "Add Path", None, QtGui.QApplication.UnicodeUTF8))
        self.DeletePath.setText(QtGui.QApplication.translate("MainWindow", "Delete Path", None, QtGui.QApplication.UnicodeUTF8))
        self.AssociateGroup.setTitle(QtGui.QApplication.translate("MainWindow", "Associate", None, QtGui.QApplication.UnicodeUTF8))
        self.WhenEnd.setText(QtGui.QApplication.translate("MainWindow", "When end", None, QtGui.QApplication.UnicodeUTF8))
        self.WhenPlayerIsFound.setText(QtGui.QApplication.translate("MainWindow", "When Player is found", None, QtGui.QApplication.UnicodeUTF8))
        self.AssociateButton.setText(QtGui.QApplication.translate("MainWindow", "Associate", None, QtGui.QApplication.UnicodeUTF8))
        self.PenwidthGroup.setTitle(QtGui.QApplication.translate("MainWindow", "Pen Width", None, QtGui.QApplication.UnicodeUTF8))
        self.MonsterGroup.setTitle(QtGui.QApplication.translate("MainWindow", "Monster", None, QtGui.QApplication.UnicodeUTF8))
        self.PreviewLabel.setText(QtGui.QApplication.translate("MainWindow", "Preview", None, QtGui.QApplication.UnicodeUTF8))
        self.SizeLabel.setText(QtGui.QApplication.translate("MainWindow", "Size", None, QtGui.QApplication.UnicodeUTF8))
        self.ColorLabel.setText(QtGui.QApplication.translate("MainWindow", "Color", None, QtGui.QApplication.UnicodeUTF8))
        self.AddChange.setText(QtGui.QApplication.translate("MainWindow", "Add/Change", None, QtGui.QApplication.UnicodeUTF8))
        self.GlobalGroup.setTitle(QtGui.QApplication.translate("MainWindow", "Global", None, QtGui.QApplication.UnicodeUTF8))
        self.Animate.setText(QtGui.QApplication.translate("MainWindow", "Animate", None, QtGui.QApplication.UnicodeUTF8))
        self.Save.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))

