# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\Twinkle Star Sprites\NTSSP\Formation Editor\src\FormationEditor.ui'
#
# Created: Fri Oct 24 23:52:25 2008
#      by: PyQt4 UI code generator 4.4.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(894,814)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setGeometry(QtCore.QRect(0,21,894,774))
        self.centralwidget.setObjectName("centralwidget")
        self.hboxlayout = QtGui.QHBoxLayout(self.centralwidget)
        self.hboxlayout.setObjectName("hboxlayout")
        self.Preview = QtGui.QGroupBox(self.centralwidget)
        self.Preview.setObjectName("Preview")
        self.gridlayout = QtGui.QGridLayout(self.Preview)
        self.gridlayout.setObjectName("gridlayout")
        self.PreviewArea = QtGui.QScrollArea(self.Preview)
        self.PreviewArea.setWidgetResizable(False)
        self.PreviewArea.setObjectName("PreviewArea")
        self.gridlayout.addWidget(self.PreviewArea,0,0,1,1)
        self.hboxlayout.addWidget(self.Preview)
        self.ToolBox = QtGui.QGroupBox(self.centralwidget)
        self.ToolBox.setMaximumSize(QtCore.QSize(350,16777215))
        self.ToolBox.setBaseSize(QtCore.QSize(100,0))
        self.ToolBox.setObjectName("ToolBox")
        self.vboxlayout = QtGui.QVBoxLayout(self.ToolBox)
        self.vboxlayout.setObjectName("vboxlayout")
        self.ToolsTabs = QtGui.QTabWidget(self.ToolBox)
        self.ToolsTabs.setObjectName("ToolsTabs")
        self.tab = QtGui.QWidget()
        self.tab.setGeometry(QtCore.QRect(0,0,324,695))
        self.tab.setObjectName("tab")
        self.verticalLayout = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.PathGroup = QtGui.QGroupBox(self.tab)
        self.PathGroup.setObjectName("PathGroup")
        self.vboxlayout1 = QtGui.QVBoxLayout(self.PathGroup)
        self.vboxlayout1.setObjectName("vboxlayout1")
        self.Curve = QtGui.QRadioButton(self.PathGroup)
        self.Curve.setChecked(True)
        self.Curve.setObjectName("Curve")
        self.vboxlayout1.addWidget(self.Curve)
        self.Line = QtGui.QRadioButton(self.PathGroup)
        self.Line.setObjectName("Line")
        self.vboxlayout1.addWidget(self.Line)
        self.Path_Add = QtGui.QPushButton(self.PathGroup)
        self.Path_Add.setObjectName("Path_Add")
        self.vboxlayout1.addWidget(self.Path_Add)
        self.Path_Delete = QtGui.QPushButton(self.PathGroup)
        self.Path_Delete.setObjectName("Path_Delete")
        self.vboxlayout1.addWidget(self.Path_Delete)
        self.label_3 = QtGui.QLabel(self.PathGroup)
        self.label_3.setMaximumSize(QtCore.QSize(16777215,20))
        self.label_3.setObjectName("label_3")
        self.vboxlayout1.addWidget(self.label_3)
        self.Path_EffectStyle = QtGui.QComboBox(self.PathGroup)
        self.Path_EffectStyle.setObjectName("Path_EffectStyle")
        self.vboxlayout1.addWidget(self.Path_EffectStyle)
        self.verticalLayout.addWidget(self.PathGroup)
        self.PenwidthGroup = QtGui.QGroupBox(self.tab)
        self.PenwidthGroup.setObjectName("PenwidthGroup")
        self.vboxlayout2 = QtGui.QVBoxLayout(self.PenwidthGroup)
        self.vboxlayout2.setObjectName("vboxlayout2")
        self.PenWidthSlider = QtGui.QSlider(self.PenwidthGroup)
        self.PenWidthSlider.setOrientation(QtCore.Qt.Horizontal)
        self.PenWidthSlider.setObjectName("PenWidthSlider")
        self.vboxlayout2.addWidget(self.PenWidthSlider)
        self.verticalLayout.addWidget(self.PenwidthGroup)
        self.GlobalGroup = QtGui.QGroupBox(self.tab)
        self.GlobalGroup.setObjectName("GlobalGroup")
        self.vboxlayout3 = QtGui.QVBoxLayout(self.GlobalGroup)
        self.vboxlayout3.setObjectName("vboxlayout3")
        self.Animate = QtGui.QPushButton(self.GlobalGroup)
        self.Animate.setObjectName("Animate")
        self.vboxlayout3.addWidget(self.Animate)
        self.Save = QtGui.QPushButton(self.GlobalGroup)
        self.Save.setObjectName("Save")
        self.vboxlayout3.addWidget(self.Save)
        self.verticalLayout.addWidget(self.GlobalGroup)
        self.ToolsTabs.addTab(self.tab,"")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setGeometry(QtCore.QRect(0,0,324,695))
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Formation_GroupsGroup = QtGui.QGroupBox(self.tab_2)
        self.Formation_GroupsGroup.setObjectName("Formation_GroupsGroup")
        self.vboxlayout4 = QtGui.QVBoxLayout(self.Formation_GroupsGroup)
        self.vboxlayout4.setObjectName("vboxlayout4")
        self.Formation_GroupsList = QtGui.QTreeWidget(self.Formation_GroupsGroup)
        self.Formation_GroupsList.setObjectName("Formation_GroupsList")
        self.vboxlayout4.addWidget(self.Formation_GroupsList)
        self.Groups_Add = QtGui.QPushButton(self.Formation_GroupsGroup)
        self.Groups_Add.setObjectName("Groups_Add")
        self.vboxlayout4.addWidget(self.Groups_Add)
        self.Groups_Change = QtGui.QPushButton(self.Formation_GroupsGroup)
        self.Groups_Change.setObjectName("Groups_Change")
        self.vboxlayout4.addWidget(self.Groups_Change)
        self.Groups_Delete = QtGui.QPushButton(self.Formation_GroupsGroup)
        self.Groups_Delete.setObjectName("Groups_Delete")
        self.vboxlayout4.addWidget(self.Groups_Delete)
        self.verticalLayout_3.addWidget(self.Formation_GroupsGroup)
        self.Formation_MonstersGroup = QtGui.QGroupBox(self.tab_2)
        self.Formation_MonstersGroup.setObjectName("Formation_MonstersGroup")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.Formation_MonstersGroup)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Formation_MonstersList = QtGui.QTreeWidget(self.Formation_MonstersGroup)
        self.Formation_MonstersList.setObjectName("Formation_MonstersList")
        self.verticalLayout_2.addWidget(self.Formation_MonstersList)
        self.label = QtGui.QLabel(self.Formation_MonstersGroup)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.Monster_Color = QtGui.QSlider(self.Formation_MonstersGroup)
        self.Monster_Color.setMinimum(1)
        self.Monster_Color.setMaximum(5)
        self.Monster_Color.setOrientation(QtCore.Qt.Horizontal)
        self.Monster_Color.setTickPosition(QtGui.QSlider.TicksAbove)
        self.Monster_Color.setTickInterval(1)
        self.Monster_Color.setObjectName("Monster_Color")
        self.verticalLayout_2.addWidget(self.Monster_Color)
        self.label_2 = QtGui.QLabel(self.Formation_MonstersGroup)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.Monster_Size = QtGui.QSlider(self.Formation_MonstersGroup)
        self.Monster_Size.setMinimum(1)
        self.Monster_Size.setMaximum(5)
        self.Monster_Size.setOrientation(QtCore.Qt.Horizontal)
        self.Monster_Size.setTickPosition(QtGui.QSlider.TicksAbove)
        self.Monster_Size.setTickInterval(1)
        self.Monster_Size.setObjectName("Monster_Size")
        self.verticalLayout_2.addWidget(self.Monster_Size)
        self.Monsters_Add = QtGui.QPushButton(self.Formation_MonstersGroup)
        self.Monsters_Add.setObjectName("Monsters_Add")
        self.verticalLayout_2.addWidget(self.Monsters_Add)
        self.Monsters_Change = QtGui.QPushButton(self.Formation_MonstersGroup)
        self.Monsters_Change.setObjectName("Monsters_Change")
        self.verticalLayout_2.addWidget(self.Monsters_Change)
        self.Monsters_Delete = QtGui.QPushButton(self.Formation_MonstersGroup)
        self.Monsters_Delete.setObjectName("Monsters_Delete")
        self.verticalLayout_2.addWidget(self.Monsters_Delete)
        self.verticalLayout_3.addWidget(self.Formation_MonstersGroup)
        self.ToolsTabs.addTab(self.tab_2,"")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setGeometry(QtCore.QRect(0,0,324,695))
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tab_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.Association_AssociationGroup = QtGui.QGroupBox(self.tab_3)
        self.Association_AssociationGroup.setObjectName("Association_AssociationGroup")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.Association_AssociationGroup)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_4 = QtGui.QLabel(self.Association_AssociationGroup)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_5.addWidget(self.label_4)
        self.Association_GroupsList = QtGui.QTreeWidget(self.Association_AssociationGroup)
        self.Association_GroupsList.setObjectName("Association_GroupsList")
        self.verticalLayout_5.addWidget(self.Association_GroupsList)
        self.label_5 = QtGui.QLabel(self.Association_AssociationGroup)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_5.addWidget(self.label_5)
        self.Association_PathsList = QtGui.QTreeWidget(self.Association_AssociationGroup)
        self.Association_PathsList.setObjectName("Association_PathsList")
        self.verticalLayout_5.addWidget(self.Association_PathsList)
        self.Association_Associate = QtGui.QPushButton(self.Association_AssociationGroup)
        self.Association_Associate.setObjectName("Association_Associate")
        self.verticalLayout_5.addWidget(self.Association_Associate)
        self.label_6 = QtGui.QLabel(self.Association_AssociationGroup)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_5.addWidget(self.label_6)
        self.Association_Type = QtGui.QComboBox(self.Association_AssociationGroup)
        self.Association_Type.setObjectName("Association_Type")
        self.verticalLayout_5.addWidget(self.Association_Type)
        self.label_7 = QtGui.QLabel(self.Association_AssociationGroup)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_5.addWidget(self.label_7)
        self.Association_TimeBefore = QtGui.QSlider(self.Association_AssociationGroup)
        self.Association_TimeBefore.setOrientation(QtCore.Qt.Horizontal)
        self.Association_TimeBefore.setObjectName("Association_TimeBefore")
        self.verticalLayout_5.addWidget(self.Association_TimeBefore)
        self.verticalLayout_4.addWidget(self.Association_AssociationGroup)
        self.ToolsTabs.addTab(self.tab_3,"")
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setGeometry(QtCore.QRect(0,0,324,695))
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.tab_4)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.Time_GroupsGroup = QtGui.QGroupBox(self.tab_4)
        self.Time_GroupsGroup.setObjectName("Time_GroupsGroup")
        self._2 = QtGui.QVBoxLayout(self.Time_GroupsGroup)
        self._2.setObjectName("_2")
        self.Time_GroupsList = QtGui.QTreeWidget(self.Time_GroupsGroup)
        self.Time_GroupsList.setObjectName("Time_GroupsList")
        self._2.addWidget(self.Time_GroupsList)
        self.verticalLayout_8.addWidget(self.Time_GroupsGroup)
        self.Time_OrderGroup = QtGui.QGroupBox(self.tab_4)
        self.Time_OrderGroup.setObjectName("Time_OrderGroup")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.Time_OrderGroup)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.Time_GroupOrder = QtGui.QListWidget(self.Time_OrderGroup)
        self.Time_GroupOrder.setObjectName("Time_GroupOrder")
        self.verticalLayout_6.addWidget(self.Time_GroupOrder)
        self.Time_OrderUp = QtGui.QPushButton(self.Time_OrderGroup)
        self.Time_OrderUp.setObjectName("Time_OrderUp")
        self.verticalLayout_6.addWidget(self.Time_OrderUp)
        self.Time_OrderDown = QtGui.QPushButton(self.Time_OrderGroup)
        self.Time_OrderDown.setObjectName("Time_OrderDown")
        self.verticalLayout_6.addWidget(self.Time_OrderDown)
        self.verticalLayout_8.addWidget(self.Time_OrderGroup)
        self.Time_OrderGlobalGroup = QtGui.QGroupBox(self.tab_4)
        self.Time_OrderGlobalGroup.setObjectName("Time_OrderGlobalGroup")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.Time_OrderGlobalGroup)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.Time_GroupTimeGlobal = QtGui.QTreeWidget(self.Time_OrderGlobalGroup)
        self.Time_GroupTimeGlobal.setObjectName("Time_GroupTimeGlobal")
        self.verticalLayout_7.addWidget(self.Time_GroupTimeGlobal)
        self.Time_OrderGlobalUp = QtGui.QPushButton(self.Time_OrderGlobalGroup)
        self.Time_OrderGlobalUp.setObjectName("Time_OrderGlobalUp")
        self.verticalLayout_7.addWidget(self.Time_OrderGlobalUp)
        self.Time_OrderGlobalDown = QtGui.QPushButton(self.Time_OrderGlobalGroup)
        self.Time_OrderGlobalDown.setObjectName("Time_OrderGlobalDown")
        self.verticalLayout_7.addWidget(self.Time_OrderGlobalDown)
        self.verticalLayout_8.addWidget(self.Time_OrderGlobalGroup)
        self.ToolsTabs.addTab(self.tab_4,"")
        self.vboxlayout.addWidget(self.ToolsTabs)
        self.hboxlayout.addWidget(self.ToolBox)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0,0,894,21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setGeometry(QtCore.QRect(0,795,894,19))
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.ToolsTabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.Preview.setTitle(QtGui.QApplication.translate("MainWindow", "Preview", None, QtGui.QApplication.UnicodeUTF8))
        self.ToolBox.setTitle(QtGui.QApplication.translate("MainWindow", "Tools", None, QtGui.QApplication.UnicodeUTF8))
        self.PathGroup.setTitle(QtGui.QApplication.translate("MainWindow", "Path", None, QtGui.QApplication.UnicodeUTF8))
        self.Curve.setText(QtGui.QApplication.translate("MainWindow", "Curve", None, QtGui.QApplication.UnicodeUTF8))
        self.Line.setText(QtGui.QApplication.translate("MainWindow", "Line", None, QtGui.QApplication.UnicodeUTF8))
        self.Path_Add.setText(QtGui.QApplication.translate("MainWindow", "Add Path", None, QtGui.QApplication.UnicodeUTF8))
        self.Path_Delete.setText(QtGui.QApplication.translate("MainWindow", "Delete Path", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Effect Style", None, QtGui.QApplication.UnicodeUTF8))
        self.Path_EffectStyle.addItem(QtGui.QApplication.translate("MainWindow", "Normal", None, QtGui.QApplication.UnicodeUTF8))
        self.Path_EffectStyle.addItem(QtGui.QApplication.translate("MainWindow", "Fixed", None, QtGui.QApplication.UnicodeUTF8))
        self.Path_EffectStyle.addItem(QtGui.QApplication.translate("MainWindow", "Circle", None, QtGui.QApplication.UnicodeUTF8))
        self.Path_EffectStyle.addItem(QtGui.QApplication.translate("MainWindow", "Switch", None, QtGui.QApplication.UnicodeUTF8))
        self.Path_EffectStyle.addItem(QtGui.QApplication.translate("MainWindow", "Rotate", None, QtGui.QApplication.UnicodeUTF8))
        self.Path_EffectStyle.addItem(QtGui.QApplication.translate("MainWindow", "Arc", None, QtGui.QApplication.UnicodeUTF8))
        self.PenwidthGroup.setTitle(QtGui.QApplication.translate("MainWindow", "Pen Width", None, QtGui.QApplication.UnicodeUTF8))
        self.GlobalGroup.setTitle(QtGui.QApplication.translate("MainWindow", "Global", None, QtGui.QApplication.UnicodeUTF8))
        self.Animate.setText(QtGui.QApplication.translate("MainWindow", "Animate", None, QtGui.QApplication.UnicodeUTF8))
        self.Save.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.ToolsTabs.setTabText(self.ToolsTabs.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Paths", None, QtGui.QApplication.UnicodeUTF8))
        self.Formation_GroupsGroup.setTitle(QtGui.QApplication.translate("MainWindow", "Groups", None, QtGui.QApplication.UnicodeUTF8))
        self.Formation_GroupsList.headerItem().setText(0,QtGui.QApplication.translate("MainWindow", "Objects", None, QtGui.QApplication.UnicodeUTF8))
        self.Formation_GroupsList.headerItem().setText(1,QtGui.QApplication.translate("MainWindow", "Description", None, QtGui.QApplication.UnicodeUTF8))
        self.Formation_GroupsList.clear()
        item = QtGui.QTreeWidgetItem(self.Formation_GroupsList)
        item.setText(0,QtGui.QApplication.translate("MainWindow", "Group1", None, QtGui.QApplication.UnicodeUTF8))
        item.setText(1,"")
        item1 = QtGui.QTreeWidgetItem(item)
        item1.setText(0,QtGui.QApplication.translate("MainWindow", "Monsters", None, QtGui.QApplication.UnicodeUTF8))
        item1.setText(1,"")
        item2 = QtGui.QTreeWidgetItem(item1)
        item2.setText(0,QtGui.QApplication.translate("MainWindow", "M1", None, QtGui.QApplication.UnicodeUTF8))
        item2.setText(1,"")
        item3 = QtGui.QTreeWidgetItem(item1)
        item3.setText(0,QtGui.QApplication.translate("MainWindow", "M2", None, QtGui.QApplication.UnicodeUTF8))
        item3.setText(1,"")
        item4 = QtGui.QTreeWidgetItem(item)
        item4.setText(0,QtGui.QApplication.translate("MainWindow", "Paths", None, QtGui.QApplication.UnicodeUTF8))
        item4.setText(1,"")
        item5 = QtGui.QTreeWidgetItem(item4)
        item5.setText(0,QtGui.QApplication.translate("MainWindow", "P2", None, QtGui.QApplication.UnicodeUTF8))
        item5.setText(1,"")
        item6 = QtGui.QTreeWidgetItem(item4)
        item6.setText(0,QtGui.QApplication.translate("MainWindow", "P3", None, QtGui.QApplication.UnicodeUTF8))
        item6.setText(1,"")
        self.Groups_Add.setText(QtGui.QApplication.translate("MainWindow", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.Groups_Change.setText(QtGui.QApplication.translate("MainWindow", "Change", None, QtGui.QApplication.UnicodeUTF8))
        self.Groups_Delete.setText(QtGui.QApplication.translate("MainWindow", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.Formation_MonstersGroup.setTitle(QtGui.QApplication.translate("MainWindow", "Monsters", None, QtGui.QApplication.UnicodeUTF8))
        self.Formation_MonstersList.headerItem().setText(0,QtGui.QApplication.translate("MainWindow", "Objects", None, QtGui.QApplication.UnicodeUTF8))
        self.Formation_MonstersList.headerItem().setText(1,QtGui.QApplication.translate("MainWindow", "Description", None, QtGui.QApplication.UnicodeUTF8))
        self.Formation_MonstersList.clear()
        item7 = QtGui.QTreeWidgetItem(self.Formation_MonstersList)
        item7.setText(0,QtGui.QApplication.translate("MainWindow", "Monster1", None, QtGui.QApplication.UnicodeUTF8))
        item7.setText(1,"")
        item8 = QtGui.QTreeWidgetItem(item7)
        item8.setText(0,QtGui.QApplication.translate("MainWindow", "Group1", None, QtGui.QApplication.UnicodeUTF8))
        item8.setText(1,"")
        item9 = QtGui.QTreeWidgetItem(item7)
        item9.setText(0,QtGui.QApplication.translate("MainWindow", "Group2", None, QtGui.QApplication.UnicodeUTF8))
        item9.setText(1,"")
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Color", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Size", None, QtGui.QApplication.UnicodeUTF8))
        self.Monsters_Add.setText(QtGui.QApplication.translate("MainWindow", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.Monsters_Change.setText(QtGui.QApplication.translate("MainWindow", "Change", None, QtGui.QApplication.UnicodeUTF8))
        self.Monsters_Delete.setText(QtGui.QApplication.translate("MainWindow", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.ToolsTabs.setTabText(self.ToolsTabs.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Formation", None, QtGui.QApplication.UnicodeUTF8))
        self.Association_AssociationGroup.setTitle(QtGui.QApplication.translate("MainWindow", "Association", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Groups", None, QtGui.QApplication.UnicodeUTF8))
        self.Association_GroupsList.headerItem().setText(0,QtGui.QApplication.translate("MainWindow", "Objects", None, QtGui.QApplication.UnicodeUTF8))
        self.Association_GroupsList.headerItem().setText(1,QtGui.QApplication.translate("MainWindow", "Description", None, QtGui.QApplication.UnicodeUTF8))
        self.Association_GroupsList.clear()
        item10 = QtGui.QTreeWidgetItem(self.Association_GroupsList)
        item10.setText(0,QtGui.QApplication.translate("MainWindow", "Group1", None, QtGui.QApplication.UnicodeUTF8))
        item10.setText(1,"")
        item11 = QtGui.QTreeWidgetItem(item10)
        item11.setText(0,QtGui.QApplication.translate("MainWindow", "Monsters", None, QtGui.QApplication.UnicodeUTF8))
        item11.setText(1,"")
        item12 = QtGui.QTreeWidgetItem(item11)
        item12.setText(0,QtGui.QApplication.translate("MainWindow", "M1", None, QtGui.QApplication.UnicodeUTF8))
        item12.setText(1,"")
        item13 = QtGui.QTreeWidgetItem(item11)
        item13.setText(0,QtGui.QApplication.translate("MainWindow", "M2", None, QtGui.QApplication.UnicodeUTF8))
        item13.setText(1,"")
        item14 = QtGui.QTreeWidgetItem(item10)
        item14.setText(0,QtGui.QApplication.translate("MainWindow", "Paths", None, QtGui.QApplication.UnicodeUTF8))
        item14.setText(1,"")
        item15 = QtGui.QTreeWidgetItem(item14)
        item15.setText(0,QtGui.QApplication.translate("MainWindow", "P1", None, QtGui.QApplication.UnicodeUTF8))
        item15.setText(1,"")
        item16 = QtGui.QTreeWidgetItem(item14)
        item16.setText(0,QtGui.QApplication.translate("MainWindow", "P2", None, QtGui.QApplication.UnicodeUTF8))
        item16.setText(1,"")
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Paths", None, QtGui.QApplication.UnicodeUTF8))
        self.Association_PathsList.headerItem().setText(0,QtGui.QApplication.translate("MainWindow", "Objects", None, QtGui.QApplication.UnicodeUTF8))
        self.Association_PathsList.headerItem().setText(1,QtGui.QApplication.translate("MainWindow", "Description", None, QtGui.QApplication.UnicodeUTF8))
        self.Association_PathsList.clear()
        item17 = QtGui.QTreeWidgetItem(self.Association_PathsList)
        item17.setText(0,QtGui.QApplication.translate("MainWindow", "Path1", None, QtGui.QApplication.UnicodeUTF8))
        item17.setText(1,"")
        item18 = QtGui.QTreeWidgetItem(item17)
        item18.setText(0,QtGui.QApplication.translate("MainWindow", "Groups", None, QtGui.QApplication.UnicodeUTF8))
        item18.setText(1,"")
        item19 = QtGui.QTreeWidgetItem(item18)
        item19.setText(0,QtGui.QApplication.translate("MainWindow", "G1", None, QtGui.QApplication.UnicodeUTF8))
        item19.setText(1,"")
        item20 = QtGui.QTreeWidgetItem(item18)
        item20.setText(0,QtGui.QApplication.translate("MainWindow", "G2", None, QtGui.QApplication.UnicodeUTF8))
        item20.setText(1,"")
        self.Association_Associate.setText(QtGui.QApplication.translate("MainWindow", "Associate", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Type", None, QtGui.QApplication.UnicodeUTF8))
        self.Association_Type.addItem(QtGui.QApplication.translate("MainWindow", "Normal", None, QtGui.QApplication.UnicodeUTF8))
        self.Association_Type.addItem(QtGui.QApplication.translate("MainWindow", "When Player is Found", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Time Before : 0 s", None, QtGui.QApplication.UnicodeUTF8))
        self.ToolsTabs.setTabText(self.ToolsTabs.indexOf(self.tab_3), QtGui.QApplication.translate("MainWindow", "Association", None, QtGui.QApplication.UnicodeUTF8))
        self.Time_GroupsGroup.setTitle(QtGui.QApplication.translate("MainWindow", "Groups", None, QtGui.QApplication.UnicodeUTF8))
        self.Time_GroupsList.headerItem().setText(0,QtGui.QApplication.translate("MainWindow", "Objects", None, QtGui.QApplication.UnicodeUTF8))
        self.Time_GroupsList.headerItem().setText(1,QtGui.QApplication.translate("MainWindow", "Description", None, QtGui.QApplication.UnicodeUTF8))
        self.Time_GroupsList.clear()
        item21 = QtGui.QTreeWidgetItem(self.Time_GroupsList)
        item21.setText(0,QtGui.QApplication.translate("MainWindow", "Group1", None, QtGui.QApplication.UnicodeUTF8))
        item21.setText(1,"")
        item22 = QtGui.QTreeWidgetItem(item21)
        item22.setText(0,QtGui.QApplication.translate("MainWindow", "Monsters", None, QtGui.QApplication.UnicodeUTF8))
        item22.setText(1,"")
        item23 = QtGui.QTreeWidgetItem(item22)
        item23.setText(0,QtGui.QApplication.translate("MainWindow", "M1", None, QtGui.QApplication.UnicodeUTF8))
        item23.setText(1,"")
        item24 = QtGui.QTreeWidgetItem(item22)
        item24.setText(0,QtGui.QApplication.translate("MainWindow", "M2", None, QtGui.QApplication.UnicodeUTF8))
        item24.setText(1,"")
        item25 = QtGui.QTreeWidgetItem(item21)
        item25.setText(0,QtGui.QApplication.translate("MainWindow", "Paths", None, QtGui.QApplication.UnicodeUTF8))
        item25.setText(1,"")
        item26 = QtGui.QTreeWidgetItem(item25)
        item26.setText(0,QtGui.QApplication.translate("MainWindow", "P2", None, QtGui.QApplication.UnicodeUTF8))
        item26.setText(1,"")
        item27 = QtGui.QTreeWidgetItem(item25)
        item27.setText(0,QtGui.QApplication.translate("MainWindow", "P3", None, QtGui.QApplication.UnicodeUTF8))
        item27.setText(1,"")
        self.Time_OrderGroup.setTitle(QtGui.QApplication.translate("MainWindow", "Time Order for current group", None, QtGui.QApplication.UnicodeUTF8))
        self.Time_OrderUp.setText(QtGui.QApplication.translate("MainWindow", "Up", None, QtGui.QApplication.UnicodeUTF8))
        self.Time_OrderDown.setText(QtGui.QApplication.translate("MainWindow", "Down", None, QtGui.QApplication.UnicodeUTF8))
        self.Time_OrderGlobalGroup.setTitle(QtGui.QApplication.translate("MainWindow", "Time Order Global", None, QtGui.QApplication.UnicodeUTF8))
        self.Time_GroupTimeGlobal.headerItem().setText(0,QtGui.QApplication.translate("MainWindow", "Objects", None, QtGui.QApplication.UnicodeUTF8))
        self.Time_GroupTimeGlobal.headerItem().setText(1,QtGui.QApplication.translate("MainWindow", "Description", None, QtGui.QApplication.UnicodeUTF8))
        self.Time_GroupTimeGlobal.clear()
        item28 = QtGui.QTreeWidgetItem(self.Time_GroupTimeGlobal)
        item28.setText(0,QtGui.QApplication.translate("MainWindow", "Path1", None, QtGui.QApplication.UnicodeUTF8))
        item28.setText(1,"")
        item29 = QtGui.QTreeWidgetItem(item28)
        item29.setText(0,QtGui.QApplication.translate("MainWindow", "Group1", None, QtGui.QApplication.UnicodeUTF8))
        item29.setText(1,"")
        item30 = QtGui.QTreeWidgetItem(item29)
        item30.setText(0,QtGui.QApplication.translate("MainWindow", "M1", None, QtGui.QApplication.UnicodeUTF8))
        item30.setText(1,"")
        item31 = QtGui.QTreeWidgetItem(item29)
        item31.setText(0,QtGui.QApplication.translate("MainWindow", "M2", None, QtGui.QApplication.UnicodeUTF8))
        item31.setText(1,"")
        item32 = QtGui.QTreeWidgetItem(item28)
        item32.setText(0,QtGui.QApplication.translate("MainWindow", "Group2", None, QtGui.QApplication.UnicodeUTF8))
        item32.setText(1,"")
        item33 = QtGui.QTreeWidgetItem(item32)
        item33.setText(0,QtGui.QApplication.translate("MainWindow", "M3", None, QtGui.QApplication.UnicodeUTF8))
        item33.setText(1,"")
        item34 = QtGui.QTreeWidgetItem(item32)
        item34.setText(0,QtGui.QApplication.translate("MainWindow", "M4", None, QtGui.QApplication.UnicodeUTF8))
        item34.setText(1,"")
        self.Time_OrderGlobalUp.setText(QtGui.QApplication.translate("MainWindow", "Up", None, QtGui.QApplication.UnicodeUTF8))
        self.Time_OrderGlobalDown.setText(QtGui.QApplication.translate("MainWindow", "Down", None, QtGui.QApplication.UnicodeUTF8))
        self.ToolsTabs.setTabText(self.ToolsTabs.indexOf(self.tab_4), QtGui.QApplication.translate("MainWindow", "Time Line", None, QtGui.QApplication.UnicodeUTF8))

