# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'F:\Twinkle Star Sprites\NTSSP\Formation Editor\src\FormationEditor.ui'
#
# Created: Wed Dec 24 10:05:11 2008
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(894, 814)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.hboxlayout = QtGui.QHBoxLayout(self.centralwidget)
        self.hboxlayout.setObjectName("hboxlayout")
        self.Preview = QtGui.QGroupBox(self.centralwidget)
        self.Preview.setObjectName("Preview")
        self.gridlayout = QtGui.QGridLayout(self.Preview)
        self.gridlayout.setObjectName("gridlayout")
        self.PreviewArea = QtGui.QScrollArea(self.Preview)
        self.PreviewArea.setWidgetResizable(False)
        self.PreviewArea.setObjectName("PreviewArea")
        self.gridlayout.addWidget(self.PreviewArea, 0, 0, 1, 1)
        self.hboxlayout.addWidget(self.Preview)
        self.ToolBox = QtGui.QGroupBox(self.centralwidget)
        self.ToolBox.setMaximumSize(QtCore.QSize(350, 16777215))
        self.ToolBox.setBaseSize(QtCore.QSize(100, 0))
        self.ToolBox.setObjectName("ToolBox")
        self.vboxlayout = QtGui.QVBoxLayout(self.ToolBox)
        self.vboxlayout.setObjectName("vboxlayout")
        self.ToolsTabs = QtGui.QTabWidget(self.ToolBox)
        self.ToolsTabs.setObjectName("ToolsTabs")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.PathGroup = QtGui.QGroupBox(self.tab)
        self.PathGroup.setObjectName("PathGroup")
        self.vboxlayout1 = QtGui.QVBoxLayout(self.PathGroup)
        self.vboxlayout1.setObjectName("vboxlayout1")
        self.Curve = QtGui.QRadioButton(self.PathGroup)
        self.Curve.setChecked(True)
        self.Curve.setObjectName("Curve")
        self.vboxlayout1.addWidget(self.Curve)
        self.Line = QtGui.QRadioButton(self.PathGroup)
        self.Line.setObjectName("Line")
        self.vboxlayout1.addWidget(self.Line)
        self.Path_Add = QtGui.QPushButton(self.PathGroup)
        self.Path_Add.setObjectName("Path_Add")
        self.vboxlayout1.addWidget(self.Path_Add)
        self.Path_Delete = QtGui.QPushButton(self.PathGroup)
        self.Path_Delete.setObjectName("Path_Delete")
        self.vboxlayout1.addWidget(self.Path_Delete)
        self.verticalLayout.addWidget(self.PathGroup)
        self.PenwidthGroup = QtGui.QGroupBox(self.tab)
        self.PenwidthGroup.setObjectName("PenwidthGroup")
        self.vboxlayout2 = QtGui.QVBoxLayout(self.PenwidthGroup)
        self.vboxlayout2.setObjectName("vboxlayout2")
        self.PenWidthSlider = QtGui.QSlider(self.PenwidthGroup)
        self.PenWidthSlider.setOrientation(QtCore.Qt.Horizontal)
        self.PenWidthSlider.setObjectName("PenWidthSlider")
        self.vboxlayout2.addWidget(self.PenWidthSlider)
        self.verticalLayout.addWidget(self.PenwidthGroup)
        self.GlobalGroup = QtGui.QGroupBox(self.tab)
        self.GlobalGroup.setObjectName("GlobalGroup")
        self.vboxlayout3 = QtGui.QVBoxLayout(self.GlobalGroup)
        self.vboxlayout3.setObjectName("vboxlayout3")
        self.Animate = QtGui.QPushButton(self.GlobalGroup)
        self.Animate.setObjectName("Animate")
        self.vboxlayout3.addWidget(self.Animate)
        self.Save = QtGui.QPushButton(self.GlobalGroup)
        self.Save.setObjectName("Save")
        self.vboxlayout3.addWidget(self.Save)
        self.Load = QtGui.QPushButton(self.GlobalGroup)
        self.Load.setObjectName("Load")
        self.vboxlayout3.addWidget(self.Load)
        self.verticalLayout.addWidget(self.GlobalGroup)
        self.ToolsTabs.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.Formation_GroupsGroup = QtGui.QGroupBox(self.tab_2)
        self.Formation_GroupsGroup.setObjectName("Formation_GroupsGroup")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.Formation_GroupsGroup)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Formation_GroupsList = QtGui.QTreeWidget(self.Formation_GroupsGroup)
        self.Formation_GroupsList.setObjectName("Formation_GroupsList")
        self.verticalLayout_3.addWidget(self.Formation_GroupsList)
        self.widget_2 = QtGui.QWidget(self.Formation_GroupsGroup)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Formation_GroupSpeedLabel = QtGui.QLabel(self.widget_2)
        self.Formation_GroupSpeedLabel.setObjectName("Formation_GroupSpeedLabel")
        self.horizontalLayout_2.addWidget(self.Formation_GroupSpeedLabel)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.Formation_GroupDiffTimeLabel = QtGui.QLabel(self.widget_2)
        self.Formation_GroupDiffTimeLabel.setObjectName("Formation_GroupDiffTimeLabel")
        self.horizontalLayout_2.addWidget(self.Formation_GroupDiffTimeLabel)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.label_3 = QtGui.QLabel(self.widget_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.verticalLayout_3.addWidget(self.widget_2)
        self.widget = QtGui.QWidget(self.Formation_GroupsGroup)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Formation_GroupSpeed = QtGui.QSlider(self.widget)
        self.Formation_GroupSpeed.setMinimum(1)
        self.Formation_GroupSpeed.setMaximum(100)
        self.Formation_GroupSpeed.setOrientation(QtCore.Qt.Horizontal)
        self.Formation_GroupSpeed.setObjectName("Formation_GroupSpeed")
        self.horizontalLayout.addWidget(self.Formation_GroupSpeed)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.Formation_GroupDiffTime = QtGui.QSlider(self.widget)
        self.Formation_GroupDiffTime.setMinimum(1)
        self.Formation_GroupDiffTime.setMaximum(100)
        self.Formation_GroupDiffTime.setOrientation(QtCore.Qt.Horizontal)
        self.Formation_GroupDiffTime.setObjectName("Formation_GroupDiffTime")
        self.horizontalLayout.addWidget(self.Formation_GroupDiffTime)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.Formation_GroupEffectStyle = QtGui.QComboBox(self.widget)
        self.Formation_GroupEffectStyle.setObjectName("Formation_GroupEffectStyle")
        self.Formation_GroupEffectStyle.addItem(QtCore.QString())
        self.Formation_GroupEffectStyle.addItem(QtCore.QString())
        self.Formation_GroupEffectStyle.addItem(QtCore.QString())
        self.Formation_GroupEffectStyle.addItem(QtCore.QString())
        self.Formation_GroupEffectStyle.addItem(QtCore.QString())
        self.Formation_GroupEffectStyle.addItem(QtCore.QString())
        self.horizontalLayout.addWidget(self.Formation_GroupEffectStyle)
        self.verticalLayout_3.addWidget(self.widget)
        self.Groups_Add = QtGui.QPushButton(self.Formation_GroupsGroup)
        self.Groups_Add.setObjectName("Groups_Add")
        self.verticalLayout_3.addWidget(self.Groups_Add)
        self.Group_Edit = QtGui.QPushButton(self.Formation_GroupsGroup)
        self.Group_Edit.setObjectName("Group_Edit")
        self.verticalLayout_3.addWidget(self.Group_Edit)
        self.Groups_Change = QtGui.QPushButton(self.Formation_GroupsGroup)
        self.Groups_Change.setObjectName("Groups_Change")
        self.verticalLayout_3.addWidget(self.Groups_Change)
        self.Groups_Delete = QtGui.QPushButton(self.Formation_GroupsGroup)
        self.Groups_Delete.setObjectName("Groups_Delete")
        self.verticalLayout_3.addWidget(self.Groups_Delete)
        self.verticalLayout_8.addWidget(self.Formation_GroupsGroup)
        self.Formation_MonstersGroup = QtGui.QGroupBox(self.tab_2)
        self.Formation_MonstersGroup.setObjectName("Formation_MonstersGroup")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.Formation_MonstersGroup)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Formation_MonstersList = QtGui.QTreeWidget(self.Formation_MonstersGroup)
        self.Formation_MonstersList.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.Formation_MonstersList.setObjectName("Formation_MonstersList")
        self.verticalLayout_2.addWidget(self.Formation_MonstersList)
        self.Monster_ColorLabel = QtGui.QLabel(self.Formation_MonstersGroup)
        self.Monster_ColorLabel.setObjectName("Monster_ColorLabel")
        self.verticalLayout_2.addWidget(self.Monster_ColorLabel)
        self.Monster_Color = QtGui.QSlider(self.Formation_MonstersGroup)
        self.Monster_Color.setMinimum(1)
        self.Monster_Color.setMaximum(5)
        self.Monster_Color.setOrientation(QtCore.Qt.Horizontal)
        self.Monster_Color.setTickPosition(QtGui.QSlider.TicksAbove)
        self.Monster_Color.setTickInterval(1)
        self.Monster_Color.setObjectName("Monster_Color")
        self.verticalLayout_2.addWidget(self.Monster_Color)
        self.Monster_SizeLabel = QtGui.QLabel(self.Formation_MonstersGroup)
        self.Monster_SizeLabel.setObjectName("Monster_SizeLabel")
        self.verticalLayout_2.addWidget(self.Monster_SizeLabel)
        self.Monster_Size = QtGui.QSlider(self.Formation_MonstersGroup)
        self.Monster_Size.setMinimum(1)
        self.Monster_Size.setMaximum(5)
        self.Monster_Size.setOrientation(QtCore.Qt.Horizontal)
        self.Monster_Size.setTickPosition(QtGui.QSlider.TicksAbove)
        self.Monster_Size.setTickInterval(1)
        self.Monster_Size.setObjectName("Monster_Size")
        self.verticalLayout_2.addWidget(self.Monster_Size)
        self.Monsters_Add = QtGui.QPushButton(self.Formation_MonstersGroup)
        self.Monsters_Add.setObjectName("Monsters_Add")
        self.verticalLayout_2.addWidget(self.Monsters_Add)
        self.Monsters_Change = QtGui.QPushButton(self.Formation_MonstersGroup)
        self.Monsters_Change.setObjectName("Monsters_Change")
        self.verticalLayout_2.addWidget(self.Monsters_Change)
        self.Monsters_Delete = QtGui.QPushButton(self.Formation_MonstersGroup)
        self.Monsters_Delete.setObjectName("Monsters_Delete")
        self.verticalLayout_2.addWidget(self.Monsters_Delete)
        self.verticalLayout_8.addWidget(self.Formation_MonstersGroup)
        self.ToolsTabs.addTab(self.tab_2, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tab_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.Association_AssociationGroup = QtGui.QGroupBox(self.tab_3)
        self.Association_AssociationGroup.setObjectName("Association_AssociationGroup")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.Association_AssociationGroup)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_4 = QtGui.QLabel(self.Association_AssociationGroup)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_5.addWidget(self.label_4)
        self.Association_GroupsList = QtGui.QTreeWidget(self.Association_AssociationGroup)
        self.Association_GroupsList.setObjectName("Association_GroupsList")
        self.verticalLayout_5.addWidget(self.Association_GroupsList)
        self.label_5 = QtGui.QLabel(self.Association_AssociationGroup)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_5.addWidget(self.label_5)
        self.Association_PathsList = QtGui.QTreeWidget(self.Association_AssociationGroup)
        self.Association_PathsList.setObjectName("Association_PathsList")
        self.verticalLayout_5.addWidget(self.Association_PathsList)
        self.Association_Associate = QtGui.QPushButton(self.Association_AssociationGroup)
        self.Association_Associate.setObjectName("Association_Associate")
        self.verticalLayout_5.addWidget(self.Association_Associate)
        self.label_6 = QtGui.QLabel(self.Association_AssociationGroup)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_5.addWidget(self.label_6)
        self.Association_Type = QtGui.QComboBox(self.Association_AssociationGroup)
        self.Association_Type.setObjectName("Association_Type")
        self.Association_Type.addItem(QtCore.QString())
        self.Association_Type.addItem(QtCore.QString())
        self.verticalLayout_5.addWidget(self.Association_Type)
        self.Association_TimeLabel = QtGui.QLabel(self.Association_AssociationGroup)
        self.Association_TimeLabel.setObjectName("Association_TimeLabel")
        self.verticalLayout_5.addWidget(self.Association_TimeLabel)
        self.Association_TimeBefore = QtGui.QSlider(self.Association_AssociationGroup)
        self.Association_TimeBefore.setMaximum(100)
        self.Association_TimeBefore.setOrientation(QtCore.Qt.Horizontal)
        self.Association_TimeBefore.setObjectName("Association_TimeBefore")
        self.verticalLayout_5.addWidget(self.Association_TimeBefore)
        self.verticalLayout_4.addWidget(self.Association_AssociationGroup)
        self.ToolsTabs.addTab(self.tab_3, "")
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.tab_4)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.Time_OrderGroup = QtGui.QGroupBox(self.tab_4)
        self.Time_OrderGroup.setObjectName("Time_OrderGroup")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.Time_OrderGroup)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label = QtGui.QLabel(self.Time_OrderGroup)
        self.label.setObjectName("label")
        self.verticalLayout_6.addWidget(self.label)
        self.Time_GroupsList = QtGui.QTreeWidget(self.Time_OrderGroup)
        self.Time_GroupsList.setAutoFillBackground(False)
        self.Time_GroupsList.setObjectName("Time_GroupsList")
        self.verticalLayout_6.addWidget(self.Time_GroupsList)
        self.Time_GroupUp = QtGui.QPushButton(self.Time_OrderGroup)
        self.Time_GroupUp.setObjectName("Time_GroupUp")
        self.verticalLayout_6.addWidget(self.Time_GroupUp)
        self.Time_GroupDown = QtGui.QPushButton(self.Time_OrderGroup)
        self.Time_GroupDown.setObjectName("Time_GroupDown")
        self.verticalLayout_6.addWidget(self.Time_GroupDown)
        self.label_2 = QtGui.QLabel(self.Time_OrderGroup)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_6.addWidget(self.label_2)
        self.Time_GroupOrder = QtGui.QTreeWidget(self.Time_OrderGroup)
        self.Time_GroupOrder.setAutoFillBackground(False)
        self.Time_GroupOrder.setObjectName("Time_GroupOrder")
        self.verticalLayout_6.addWidget(self.Time_GroupOrder)
        self.Time_Delete = QtGui.QPushButton(self.Time_OrderGroup)
        self.Time_Delete.setObjectName("Time_Delete")
        self.verticalLayout_6.addWidget(self.Time_Delete)
        self.Time_OrderUp = QtGui.QPushButton(self.Time_OrderGroup)
        self.Time_OrderUp.setObjectName("Time_OrderUp")
        self.verticalLayout_6.addWidget(self.Time_OrderUp)
        self.Time_OrderDown = QtGui.QPushButton(self.Time_OrderGroup)
        self.Time_OrderDown.setObjectName("Time_OrderDown")
        self.verticalLayout_6.addWidget(self.Time_OrderDown)
        self.verticalLayout_7.addWidget(self.Time_OrderGroup)
        self.ToolsTabs.addTab(self.tab_4, "")
        self.vboxlayout.addWidget(self.ToolsTabs)
        self.hboxlayout.addWidget(self.ToolBox)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 894, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.ToolsTabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.Preview.setTitle(QtGui.QApplication.translate("MainWindow", "Preview", None, QtGui.QApplication.UnicodeUTF8))
        self.ToolBox.setTitle(QtGui.QApplication.translate("MainWindow", "Tools", None, QtGui.QApplication.UnicodeUTF8))
        self.PathGroup.setTitle(QtGui.QApplication.translate("MainWindow", "Path", None, QtGui.QApplication.UnicodeUTF8))
        self.Curve.setText(QtGui.QApplication.translate("MainWindow", "Curve", None, QtGui.QApplication.UnicodeUTF8))
        self.Line.setText(QtGui.QApplication.translate("MainWindow", "Line", None, QtGui.QApplication.UnicodeUTF8))
        self.Path_Add.setText(QtGui.QApplication.translate("MainWindow", "Add Path", None, QtGui.QApplication.UnicodeUTF8))
        self.Path_Delete.setText(QtGui.QApplication.translate("MainWindow", "Delete Path", None, QtGui.QApplication.UnicodeUTF8))
        self.PenwidthGroup.setTitle(QtGui.QApplication.translate("MainWindow", "Pen Width", None, QtGui.QApplication.UnicodeUTF8))
        self.GlobalGroup.setTitle(QtGui.QApplication.translate("MainWindow", "Global", None, QtGui.QApplication.UnicodeUTF8))
        self.Animate.setText(QtGui.QApplication.translate("MainWindow", "Animate", None, QtGui.QApplication.UnicodeUTF8))
        self.Save.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.Load.setText(QtGui.QApplication.translate("MainWindow", "Load", None, QtGui.QApplication.UnicodeUTF8))
        self.ToolsTabs.setTabText(self.ToolsTabs.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Paths", None, QtGui.QApplication.UnicodeUTF8))
        self.Formation_GroupsGroup.setTitle(QtGui.QApplication.translate("MainWindow", "Groups", None, QtGui.QApplication.UnicodeUTF8))
        self.Formation_GroupsList.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "Objects", None, QtGui.QApplication.UnicodeUTF8))
        self.Formation_GroupsList.headerItem().setText(1, QtGui.QApplication.translate("MainWindow", "Description", None, QtGui.QApplication.UnicodeUTF8))
        self.Formation_GroupSpeedLabel.setText(QtGui.QApplication.translate("MainWindow", "Speed: 0", None, QtGui.QApplication.UnicodeUTF8))
        self.Formation_GroupDiffTimeLabel.setText(QtGui.QApplication.translate("MainWindow", "DiffTime: 0s", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Effect Type:", None, QtGui.QApplication.UnicodeUTF8))
        self.Formation_GroupEffectStyle.setItemText(0, QtGui.QApplication.translate("MainWindow", "Normal", None, QtGui.QApplication.UnicodeUTF8))
        self.Formation_GroupEffectStyle.setItemText(1, QtGui.QApplication.translate("MainWindow", "Circle", None, QtGui.QApplication.UnicodeUTF8))
        self.Formation_GroupEffectStyle.setItemText(2, QtGui.QApplication.translate("MainWindow", "Switch", None, QtGui.QApplication.UnicodeUTF8))
        self.Formation_GroupEffectStyle.setItemText(3, QtGui.QApplication.translate("MainWindow", "Arc", None, QtGui.QApplication.UnicodeUTF8))
        self.Formation_GroupEffectStyle.setItemText(4, QtGui.QApplication.translate("MainWindow", "Rotate", None, QtGui.QApplication.UnicodeUTF8))
        self.Formation_GroupEffectStyle.setItemText(5, QtGui.QApplication.translate("MainWindow", "Fixed", None, QtGui.QApplication.UnicodeUTF8))
        self.Groups_Add.setText(QtGui.QApplication.translate("MainWindow", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.Group_Edit.setText(QtGui.QApplication.translate("MainWindow", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.Groups_Change.setText(QtGui.QApplication.translate("MainWindow", "Change", None, QtGui.QApplication.UnicodeUTF8))
        self.Groups_Delete.setText(QtGui.QApplication.translate("MainWindow", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.Formation_MonstersGroup.setTitle(QtGui.QApplication.translate("MainWindow", "Monsters", None, QtGui.QApplication.UnicodeUTF8))
        self.Formation_MonstersList.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "Objects", None, QtGui.QApplication.UnicodeUTF8))
        self.Formation_MonstersList.headerItem().setText(1, QtGui.QApplication.translate("MainWindow", "Description", None, QtGui.QApplication.UnicodeUTF8))
        self.Monster_ColorLabel.setText(QtGui.QApplication.translate("MainWindow", "Color : 1", None, QtGui.QApplication.UnicodeUTF8))
        self.Monster_SizeLabel.setText(QtGui.QApplication.translate("MainWindow", "Size : 1", None, QtGui.QApplication.UnicodeUTF8))
        self.Monsters_Add.setText(QtGui.QApplication.translate("MainWindow", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.Monsters_Change.setText(QtGui.QApplication.translate("MainWindow", "Change", None, QtGui.QApplication.UnicodeUTF8))
        self.Monsters_Delete.setText(QtGui.QApplication.translate("MainWindow", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.ToolsTabs.setTabText(self.ToolsTabs.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Formation", None, QtGui.QApplication.UnicodeUTF8))
        self.Association_AssociationGroup.setTitle(QtGui.QApplication.translate("MainWindow", "Association", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Groups", None, QtGui.QApplication.UnicodeUTF8))
        self.Association_GroupsList.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "Objects", None, QtGui.QApplication.UnicodeUTF8))
        self.Association_GroupsList.headerItem().setText(1, QtGui.QApplication.translate("MainWindow", "Description", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Paths", None, QtGui.QApplication.UnicodeUTF8))
        self.Association_PathsList.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "Objects", None, QtGui.QApplication.UnicodeUTF8))
        self.Association_PathsList.headerItem().setText(1, QtGui.QApplication.translate("MainWindow", "Description", None, QtGui.QApplication.UnicodeUTF8))
        self.Association_Associate.setText(QtGui.QApplication.translate("MainWindow", "Associate", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Type", None, QtGui.QApplication.UnicodeUTF8))
        self.Association_Type.setItemText(0, QtGui.QApplication.translate("MainWindow", "Normal", None, QtGui.QApplication.UnicodeUTF8))
        self.Association_Type.setItemText(1, QtGui.QApplication.translate("MainWindow", "When Player is Found", None, QtGui.QApplication.UnicodeUTF8))
        self.Association_TimeLabel.setText(QtGui.QApplication.translate("MainWindow", "Time Before : 0 s", None, QtGui.QApplication.UnicodeUTF8))
        self.ToolsTabs.setTabText(self.ToolsTabs.indexOf(self.tab_3), QtGui.QApplication.translate("MainWindow", "Association", None, QtGui.QApplication.UnicodeUTF8))
        self.Time_OrderGroup.setTitle(QtGui.QApplication.translate("MainWindow", "Groups  Order", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Global Groups Order :", None, QtGui.QApplication.UnicodeUTF8))
        self.Time_GroupsList.setSortingEnabled(False)
        self.Time_GroupsList.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "Objects", None, QtGui.QApplication.UnicodeUTF8))
        self.Time_GroupsList.headerItem().setText(1, QtGui.QApplication.translate("MainWindow", "Description", None, QtGui.QApplication.UnicodeUTF8))
        self.Time_GroupUp.setText(QtGui.QApplication.translate("MainWindow", "Up", None, QtGui.QApplication.UnicodeUTF8))
        self.Time_GroupDown.setText(QtGui.QApplication.translate("MainWindow", "Down", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Time Order For Current Group :", None, QtGui.QApplication.UnicodeUTF8))
        self.Time_GroupOrder.setSortingEnabled(False)
        self.Time_GroupOrder.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "Objects", None, QtGui.QApplication.UnicodeUTF8))
        self.Time_GroupOrder.headerItem().setText(1, QtGui.QApplication.translate("MainWindow", "Description", None, QtGui.QApplication.UnicodeUTF8))
        self.Time_Delete.setText(QtGui.QApplication.translate("MainWindow", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.Time_OrderUp.setText(QtGui.QApplication.translate("MainWindow", "Up", None, QtGui.QApplication.UnicodeUTF8))
        self.Time_OrderDown.setText(QtGui.QApplication.translate("MainWindow", "Down", None, QtGui.QApplication.UnicodeUTF8))
        self.ToolsTabs.setTabText(self.ToolsTabs.indexOf(self.tab_4), QtGui.QApplication.translate("MainWindow", "Time Line", None, QtGui.QApplication.UnicodeUTF8))

